kind: pipeline
name: beardedtek-docker-transmission
trigger:
  branch:
    - master
  event:
    - push
steps:
- name: beardedtek-PUSH
  image: plugins/docker
  when:
    event:
      - push
  settings:
    username: beardedtek
    password:
      from_secret: docker_password
    repo: docker.beardedtek.com/beardedtek-com/docker-transmission
    registry: docker.beardedtek.com
    tags: latest,${DRONE_REPO_BRANCH}
    experimental: true
    compress: true
    squash: true
image_pull_secrets:
  - docker-auth-beardedtek.com